### ISSUE TITLE
What is purpose of other scopes apart from required one at Standalone Patient Scope box.

### ISSUE THREAD

**Issue by tarunkumar985** [onc-healthit/inferno-program#122]
Hi,

when the application is looking for only three resources i.e, Patient, Condition, Observation then what is purpose of passing other scopes which are automatically populated in the box. 

however, the application is verifying the other resources that are not requested at the time of authorisation.

Suppose if user has given access to client only three resources i.e, Patient, Condition, Observation  in that case if client request for other scope then it would be rejected.

Thanks,
Tarun

![image](https://user-images.githubusercontent.com/42908566/85108069-aaad2300-b22c-11ea-9805-0fee100c531b.png)

**Comment by yunwwang** [comment]
Hello, thank you for reaching out to Inferno team. 
Inferno Program Edition is a streamlined testing tool for HL7 FHIR services seeking to meet the requirements of the Standardized API for Patient and Population Services criterion § 170.315(g)(10) in the 2015 Edition Cures Update. 
USCDI (https://www.healthit.gov/isa/united-states-core-data-interoperability-uscdi) lists all data element server must support. Inferno Program Edition follows that requirement when testing server's compatibility. In order to complete the test, Inferno must be granted privileges to access those FHIR resources listed in the scope. 
If your use case does not include all data elements required by USCDI, you can try Inferno Community Edition which is not tied to the criterion § 170.315(g)(10).

**Comment by tarunkumar985** [comment]
Thanks @yunwwang !!
