### ISSUE TITLE
Disk space requirements for run_terminology.sh

### ISSUE THREAD

**Issue by bforbis** [onc-healthit/inferno-program#126]
The README currently explains that you must have 10gb of reserved memory to build the terminologies which is useful info, but currently says nothing about free disk space required.

I just ran the terminologies script while only having about 15gb free disk space and had to frantically start deleting things off my disk faster than it could import data / build sql indexes.

**Comment by radamson** [comment]
Thanks for reporting this issue!  That's another important thing to consider that should be in the README.md.  We'll take a look at the disk requirements and add it to the README to reflect that.  As you have seen, the terminology artifacts from NLM are large 🙂 .

Out of curiosity, were you building the terminology files directly on your system with `run_terminology.sh` or with Docker `docker-compose -f terminology_compose.yml build`?

**Comment by bforbis** [comment]
I was using docker to build them. I think maybe some improvements could be done to delete the zip file after unzipping, because these are really huge zip files. Doing so at least reduces the amount of operating disk space required by 4.8gb

```
du -hd 1 *
413M    MRCONSO.pipe
1.4G    MRREL.pipe
3.3G    MRSAT.pipe
 20M    fhir
5.7G    umls/2019AB-full
5.7G    umls
6.5G    umls.db
4.8G    umls.zip
468K    umls_subset/CHANGE
8.4G    umls_subset
```

**Comment by radamson** [comment]
Right now we do have an optional "Cleanup" step which purges the `tmp` directory of terminology artifacts at the end of the process, but I do think it would be worth considering removing the intermediate artifacts as we go.  We've chosen to leave those in because it allows the terminology build process to start at the most recently finished step (i.e. if you've already downloaded UMLS then there is no need to do it again) which makes subsequent rebuilds much faster.  Also if one of the latter steps has an issue we don't have to start all over.

We'll look into the feasibility of a "limited memory mode" though because I'm sure others will run into this. Thanks again for reporting this issue and the suggestions!

**Comment by yunwwang** [comment]
Close this issue. The solution has been released
