### ISSUE TITLE
Unable to supply 2 date search parameters for CarePlan search by patient/category/date

### ISSUE THREAD

**Issue by ashu-bdvt** [onc-healthit/inferno-program#183]
**Is your feature request related to a problem? Please describe it.**
I am running inferno v2.9.0 locally and trying to validate against a locally run fhir server.

**Describe the solution you'd like to see implemented**
In our solution, we support 2 dates for CarePlan resource.
Eg: http://localhost/r4/2c4XXX-XXX-XXX-XXX5fde9f/CarePlan?patient=9898989&date=ge2020-01-08T15:40:00.000Z&date=le2020-01-08T15:40:36.000Z. 
However I do not see how to extend USCore310CareplanSequence to add such a scenario. If i supply 2 dates, it overwrites and takes the latest variable
* A description of the solution.
Seeking recommendation
* Details of the technical implementation, if you've thought about it.
* Any caveats/tradeoffs of the proposed solution.

**Describe alternatives you've considered**
Looking for suggestions.

Also would like to see if I run locally and try to validate my locally run FHIR server, does inferno reads my capability statement and adjust the tests to be run accordingly? Did not see get any clarity from the documentation

**Comment by yunwwang** [comment]
Hello ashu-bdvt:
Inferno support data range search. Your issue is that patient+date is not a mandatory search parameter specified in US Core IG so Inferno Program edition, which is tailored for US Core v3.1.0, does not have a test for it.
Inferno Program edition (and Community Edition too) does not generate tests at run time. Tests have to be pre generated using Inferno test generator.
If you want to manually modify CarePlan testing with additional patient+date test, you can take a look USCore Procedure test USCPROC-02 which tests patient+date with date range search.
As a warning, by doing this, you deviate from standard US Core profile testing.  If this is your intention, I would recommend to use Inferno Community, instead of Inferno Program, which gives you more flexibility on testing. Here is the Inferno Community Repo: https://github.com/onc-healthit/inferno

**Comment by yunwwang** [comment]
Closed as question answered
