### ISSUE TITLE
Visual Inspection and Attestation > Refresh token tests 

### ISSUE THREAD

**Issue by emily-alt** [onc-healthit/inferno-program#309]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Raising the following questions/recommendations for the refresh token tests under the Visual Inspection and Attestation section of the “Other” tab:

1. The test for **confidential client** refresh tokens currently states “Health IT Module attested that refresh tokens had three month timeout period.” As written it is not in alignment with the regulation, which requires that refresh tokens issued are valid for _at least_ three months – NOT that refresh tokens explicitly expire after three months.

2. The equivalent test for **native app** refresh tokens does not reflect the minimum three month validity requirement and indicates an expectation of _demonstrating_ support versus _attesting_ like the sister confidential refresh token test in #1 above.  "Health IT developer demonstrates support for issuing refresh tokens to native applications." Is this actually intended to be an attestation also? If not, can INF please provide direction on how this would be expected to be demonstrated?

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.6 
* Which browser and version(s) is the bug present on?: n/a

**Steps to reproduce**
Tell us how to reproduce this issue.

Review verbiage for the two refresh token tests  in the Visual Inspection and Attestation section

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.
Consider language like:
“Health IT Module attested that refresh tokens are valid for a period of no shorter than three months."
"Health IT Module attested support for issuing refresh tokens to native applications."

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by arscan** [comment]
Hi @emily-alt -- thanks for pointing these out.  I agree we are a little loose on the language here.  We'll review and make sure we pull the appropriate language so it doesn't look like we are altering any of the requirements (which wasn't our intent).

**Comment by yunwwang** [comment]
Working ticket: FI-1270

**Comment by arscan** [comment]
Hi @emily-alt --

We should have clarified exactly what we changed here, and what we didn't.  For your first point, regarding the language in Inferno not being clear that the refresh token had to be 3 months at a minimum (and not exactly 3 months, we [updated the language](https://github.com/onc-healthit/inferno-program/blob/6c08c64f6f4bbbbb9935803fbd29a5adb002596a/lib/modules/onc_program/onc_visual_inspection_sequence.rb#L90) to:  "Health IT Module attested that refresh tokens are valid for a period of no shorter than three months."

For your second point, we did not change the language because it was intentional for us to state that the health IT developer needs to demonstrate native apps receiving a refresh token, because Inferno's automated test do not cover this requirement.  We don't provide guidance in the tool about how you might go about doing this -- likely a suitable solution would be provide an example native client application that does this and show it working to the test lab.  We cannot test it automatically because you are free to layer additional requirements on apps (e.g. PKCE, dynamic registration, etc), and there is no way for us to know exactly what those might be.

One thing that we may provide eventually is an optional launch that adds PKCE, as that is a common additional standard for native clients, so if you only require that for native clients + refresh tokens then you do not need to separately demonstrate this requirement. This was a request in #297, and SMART v2 includes more specificity here, so it seems likely we will eventually have something like that in Inferno.  We do not today though.
