### ISSUE TITLE
Can the local installation of Inferno be run on https instead of http?

### ISSUE THREAD

**Issue by Puttajunjaiah01** [onc-healthit/inferno-program#314]
**Is your feature request related to a problem? Please describe it.**
The default installation of the program edition of the Inferno tool runs on http://localhost:4567. Since http protocol is insecure and our smart app creation doesn't allow http schemes in redirect uris. Can there be a way to run local installations of Inferno on https instead of http like **https**://localhost:4567

**Describe the solution you'd like to see implemented**
Local installation of Inferno running on https://localhost:4567

**Describe alternatives you've considered**
None

**Comment by arscan** [comment]
Sure, we have three options -- though all of them require some knowledge of how docker, ssl and web servers work.  Depending on your experience configuring web servers, this might be either very straightforward or pretty challenging in your environment.

Option 1) Set up a webserver on your local machine configured to use TLS and listen on port 443 to serve as a reverse proxy to inferno listening on port 4567.

Option 2) Run the entire https://inferno.healthit.gov website on your local machine by cloning the [onc-healthit/inferno.healthit.gov](https://github.com/onc-healthit/inferno.healthit.gov/) repository, which is configured for SSL.  Note that this includes a whole bunch more services than just the inferno certification tests, so you'll need to make sure docker is allocated a good amount of RAM.  Also, you'll need to uncomment two lines and comment out two lines in the configuration file: [here](https://github.com/onc-healthit/inferno.healthit.gov/blob/master/docker-compose.yml#L45-L47) and [here](https://github.com/onc-healthit/inferno.healthit.gov/blob/master/docker-compose.yml#L89-L91).

Option 3) Using the `inferno-program` repository (this one), configure the nginx server that is used to accept SSL in the same way that we have done in the option 2 above.  This requires more work, but doesn't start up all the extra services that come in inferno.healthit.gov.  In the [docker-compose.yml](https://github.com/onc-healthit/inferno.healthit.gov/blob/master/docker-compose.yml) file you'll need to expose port 443 and map a volume to a directory containing a cert.  And you'll need to update the [nginx.conf](https://github.com/onc-healthit/inferno.healthit.gov/blob/master/nginx/nginx.conf#L45) for SSL, which includes pointing it the cert in the directory you mapped in the `docker-compose` file.  You can look at the files in option 2 above for examples.

Would any of those work for you?  We've used pretty common building blocks (e.g. nginx) to allow for users to tweak their deployment if they need to, but we can only provide limited support because a lot depends on your environment.

Rob

**Comment by Puttajunjaiah01** [comment]
Thank you. That was helpful :)
