### ISSUE TITLE
Procedure Search By Date test not searching with date comparators

### ISSUE THREAD

**Issue by bh021790** [onc-healthit/inferno-program#339]
![image](https://user-images.githubusercontent.com/20422272/128562720-cec63578-94b7-44f0-bdb8-44be9b8f6971.png)
**TEST:**
USCPROC-02: Server returns valid results for Procedure search by patient+date.
A server SHALL support searching by patient+date on the Procedure resource. This test will pass if resources are returned and match the search criteria. If none are returned, the test is skipped.

This will also test support for these date comparators: gt, ge, lt, le. Comparator values are created by taking a date value from a resource returned in the first search of this sequence and adding/subtracting a day. For example, a date of 05/05/2020 will create comparator values of lt2020-05-06 and gt2020-05-04

https://www.hl7.org/fhir/us/core/CapabilityStatement-us-core-server.html

**ISSUE:**
**Our server requires a date comparator to be passed in the parameter. The Inferno test only searches by date=2003 which we  do not support. Is the test working as designed?**

Inferno Version: 1.6.2
Browser: chrome

**Comment by yunwwang** [comment]
Hello @bh021790 : Thank you for raising this issue to us. I did some investigation last weekend. I have different interpretation on US Core Procedure search requirement. The Quick Start section (http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-procedure.html#quick-start) has an expression:

`GET [base]/Procedure?patient=[reference]&date={gt|lt|ge|le}[date]{&date={gt|lt|ge|le}[date]&...}`

According to US Core search syntax (http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#search-syntax)
`Variables surrounded by “{}” are optional for the client to supply`

After removing all the "optional" parts, the base search form is  `GET [base]/Procedure?patient=[reference]&date=[date]`

This is what server is required to support.

The wording "including support for these date comparators: gt,lt,ge,le" means (on top of the base form, server need to) include support for these date comparators: gt,lt,ge,le

I believe the intention here is that server does not have to support `eq` comparator because it is the same as base search form without comparator

**Comment by yunwwang** [comment]
@bh021790 Do you have additional comment for this issue? If not, I would close this issue.

**Comment by bh021790** [comment]
Sorry for the delay! I went on maternity leave shortly after my post :) 

@yunwwang Your clarification makes sense. Thanks for breaking it down for me!

One follow up: Why does USCPROC-02 include a search by status? Status is not a required search parameter for Procedure. It's a SHOULD not a SHALL

   GET   400   https://fhir-myrecord.cerner.com/r4/17316440-14fe-4957-b62f-9d85de2c88ca/Procedure?date=1989-06-30&patient=4755812&status=preparation,in-progress,not-done,on-hold,stopped,completed,entered-in-error,unknown

**Comment by yunwwang** [comment]
@bh021790 First, congratulation!

This is based on a requirement from US Core [search with status](http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#search-for-servers-requiring-status). 

Based on the behavior, I would assume that cerner server does not allow searching Procedure without status. So the first search (without status) returned status code 400.

**Comment by bh021790** [comment]
@yunwwang thank you! 

So I read that US Core guidance to mean that we only need to follow the guidance IF our server requires search by status,  which it doesn't. Since our server doesn't require status and we don't support the parameter for Procedure, that  test should  be  omitted/skipped for us.  What am I missing/misinterpreting?

**Comment by yunwwang** [comment]
Hmm, that is strange because Inferno tests USCPROC-02 by searching with patient+date first. If the search result is 400, then Inferno changes to search with patient+date+search. 
Can you take a look of the test result of USCPROC-02? If the first search returned http 400 and if so, what the error message is.

![image](https://user-images.githubusercontent.com/8761175/153262934-678874f4-5873-40d1-9041-509d837dc4dd.png)

**Comment by bh021790** [comment]
The way we support date search needs to be fixed so we throw a 400 right now (incorrectly)
![image](https://user-images.githubusercontent.com/20422272/153265120-0750a08e-b401-466d-8e57-160ad7ef6ebd.png)

same window  (scrolled right to show search params):
![image](https://user-images.githubusercontent.com/20422272/153265213-d0fffab7-5798-47a6-8ff3-754003fcaecc.png)

**Comment by yunwwang** [comment]
OK. I got that. Since the server returns 400 for the first query (for the separate reason we discussed before), Inferno automatically run the second search with status. The reason is that US Core "search with status" only says that 

* SHALL return an http 400 status
* SHALL return an [OperationOutcome](http://hl7.org/fhir/R4/operationoutcome.html) specifying that status(es) must be present.

For the 2nd bullet point, US Core does not specify how the server "specifying that status(es) must be present" which means that Inferno could not use a specific error code or message to determine of a HTTP 400 has the meaning "status(es) must be present". So Inferno treats every 400 result by sending another searching with status if the resource type has status element and search parameter.

I think this behavior will go away after your serer fixes the searching by date problem.
