### ISSUE TITLE
Inferno test  SPB-OSLS-10 failed when patient/Person.read  is added to the Standalone Patient Scope (FI-1351)

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/inferno-program#372]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.
See Issue description

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.7.0
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.
Start running Inferno. Add patient/Person.read to the Standalone Patient Scope before the series of the Standalone Patient App - Full Patient Access tests run. Populate the rest of the input fields as needed. Press Execute. 

Test SPB-OSLS-10 fails with the following error:
'Person' must be either a valid resource type or '*'
![image](https://user-images.githubusercontent.com/73243391/135672981-b3437e49-c91c-426d-990b-63cdba3faf6b.png)

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by IgLysk00** [comment]
Also, Inferno should accept user/Person.read for the proxy.

**Comment by yunwwang** [comment]
This is the same (or similar) issue as #362

**Comment by arscan** [comment]
Do you need Inferno (as a client) to request patient/Person.read in order for something to work?  If so, for what (OpenID Connect maybe)? Or do you only need Inferno to be able to accept that scope being granted (even if Inferno did not request it?)

We'd fail in either case today, but we are considering these as two different cases because it may be the case that we should be very strict about what clients have to request to get USCDI data but be very lenient in allowing extra scopes be granted (which is allowed by OAuth).

Also, could you explain what you mean by proxy?

**Comment by sudhir80** [comment]
We'd like Inferno to not error out when we add user/Person.read scope (we manually add this scope) to the requested scopes list. We add this so Inferno can resolve "Person" resource that's returned in fhirUser claim of the id_token when Inferno requests for "openid fhirUser" scopes for the "patient" persona (see "OIDC-07: Test Details: FHIR resource representing the current user can be retrieved). Since Inferno does not request for Person.read scope by default, that's needed for OIDC-07 test, we are adding it manually and Inferno does not seem to like it.

"proxy" meant a person authorized to access patient's medical records on patient's behalf. In this scenario fhirUser claim contains Person resource URL.

**Comment by arscan** [comment]
Thanks.  Since the client has no way of knowing ahead of time which of the allowable resources this information may be served from (Person, Practitioner, Patient, RelatedPerson), I was wondering if the correct behavior would be for servers to grant access to the resource along with the `fhirUser` scope, and not have to have clients proactively ask for full user access to all four resource types because they want to make sure they cover all possible cases.  But on the other hand, the guide isn't really specific about what is required here, and since `Person` is specifically called out as a potential location perhaps the test should just allow servers to require them to include that if needed.

**Comment by yunwwang** [comment]
SMART App Launch Framework IG says that 
```quote
Note that Person is only used if the other resource type do not apply to the current user, for example, the “authorized representative” for >1 patients.
```

**Comment by sudhir80** [comment]
Yes @yunwwang. Soarian Clinicals EHR is also using `Person` resource for the authorized representative (a.k.a. proxy) user scenario only. If the API user is the patient accessing medical data for self, then the `fhirUser` claim URL is for the `Patient` resource. For the provider user, `fhirUser` claim URL is for the `Practitioner` resource. Soarian Clinicals does not support `RelatedPerson` resource.

**Comment by sudhir80** [comment]
@arscan, in the context of `fhirUser` `Practitioner` resource comes into play only in case of provider user I believe, since the patient access user will not be the `Practitioner` himself/herself. So, I believe it's safe to say that the app acting on behalf of a provider can safely assume that the `fhirUser` URL is a `Practitioner` resource URL and nothing else.

For the patient access use case, the `fhirUser` claim can be one of the `Patient`, `Person` or `RelatedPerson`, the app does not have a way to know beforehand. So, I think that the right behavior would be for the app to proactively request for corresponding `.read`  scope for all three resources along with `fhirUser` scope during initial authorization request.

**Comment by yunwwang** [comment]
@sudhir80 based on your description, this should be `RelatedPerson` because `Person` is pure demographic while `RelatedPerson` is source of information. And the example of RelatedPerson include
```quote
A patient's attorney or guardian
```
which aligns with what you described as "the authorized representative (a.k.a. proxy) user"

**Comment by yunwwang** [comment]
Sorry, I clicked the close button by mistake. I thought it was the "comment" button. Re-open the ticket.

**Comment by yunwwang** [comment]
@IgLysk00 @sudhir80 Inferno v1.8.0 is released. Could you verify that this issue has been addressed in this release?

**Comment by IgLysk00** [comment]
Ran Inferno with option user/Person.read. So far no issues found. Thanks.
