### ISSUE TITLE
Standalone Launch Sequence redirects to Bulk Data tests

### ISSUE THREAD

**Issue by awatson1978** [onc-healthit/inferno-program#424]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.

Hello, when running the SMART on FHIR Standalone Launch Sequence, Inferno redirects to Bulk Data tests.

<img width="1422" alt="Screen Shot 2021-12-22 at 10 09 52 AM" src="https://user-images.githubusercontent.com/675910/147122075-a61ae5c6-df05-4d2e-898b-43050d42a7a1.png">

<img width="1422" alt="Screen Shot 2021-12-22 at 10 10 00 AM" src="https://user-images.githubusercontent.com/675910/147122104-7e9a7eb0-28a4-499f-8ad5-4d954fbc3982.png">

<img width="1422" alt="Screen Shot 2021-12-22 at 10 10 04 AM" src="https://user-images.githubusercontent.com/675910/147122119-198a3e01-4344-459e-8aad-7348af162ddc.png">

**Your environment**
* Edition of inferno (Community or Program):  Community
* Version of inferno:  Current
* Which browser and version(s) is the bug present on?:  Chrome

**Steps to reproduce**
Tell us how to reproduce this issue.

Testing against https://vhdir.meteorapp.com

**Expected behavior**
Not pulling up the RiteAid Bulk Data tests?  Seems like a leaky session variable or state value.  When inspecting the state values, a RiteAid server appears.  I would expect this to be https://vhdir.meteorapp.com, based on the launch test we began.  And for this not to be the Bulk Data server.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

<img width="1422" alt="Screen Shot 2021-12-22 at 10 13 48 AM" src="https://user-images.githubusercontent.com/675910/147122542-80b94c6e-87a2-40b8-8871-b09b8391c1f2.png">

**Comment by yunwwang** [comment]
@awatson1978 Are you testing SMART Schedule Links?

**Comment by awatson1978** [comment]
No.  I'm testing Standalone Launch Sequence, and it redirects me to a completely unrelated page.

**Comment by arscan** [comment]
Did you click 'Continue' and it immediately redirected you there?  Or did it go to your systems authorization screen?

One thing we try to do to be helpful is that if the system under test doesn't properly obey OAuth and doesn't send us back the right `state` parameter, we store the testing instance id in a cookie and use that to get the user back to the right test session.  So that could be the source of the issue here.

**Comment by awatson1978** [comment]
Just clicked 'Continue' and it immediately redirected me there.  Haven't seen a Systems Authorization screen, to my knowledge.  Other than the Stand Alone Launch panel.  

Clearing cookies did occur to me.  And I can double check the state parameter; make sure it's properly formed.

**Comment by arscan** [comment]
Do you know if, perhaps sometime in the long distance past, you ran those SMART Scheduling Links tests?  The most likely thing seems to me that we stored the session info then, and then for some reason something is getting mixed up for you now and Inferno is sending you back to that old session.  The only time this could happen is during SMART launches -- we don't use cookies otherwise (it is the last-ditch effort to send you somewhere useful instead of just an error page saying we do not know where you are supposed to go because you didn't do OAuth quite right).

Even if that is the case, something is not working quite right because it should overwrite that session info cookie with the new session when you click 'continue'.  But at least it would explain where that URL is coming from, and we aren't sending you to someone else's test data.

**Comment by arscan** [comment]
I think I found the issue.  If you go to Inferno Community's redirect URL without any `state` param attached, it seems to always dump you at this session.  We will address this.

For your system, make sure you add that state parameter when redirecting back to Inferno.

Note that this only affects 'inferno community edition' and not 'inferno program edition' (so this ticket is misfiled technically, but I know it isn't very clear right now where to file these questions).

**Comment by awatson1978** [comment]
Not having the correct `state` parameter - totally my fault.  Anything to do with RiteAid, not my fault.  ;)

**Comment by arscan** [comment]
I moved this issue over to the `Inferno Community` repository as this only applies to tests maintained there.

Thanks!
