### ISSUE TITLE
Practitioner , location , medication , organisation and PractitionerRole are not required separately in BULK DATA test

### ISSUE THREAD

**Issue by tarunkumar985** [onc-healthit/inferno-program#81]
As per HL7 document above mentioned resources are not included for separate bulk data test; But inferno takes it as individual test. we don't have patient's id listed in those resources.

Thanks,
![image](https://user-images.githubusercontent.com/42908566/82439520-6f49f800-9ab8-11ea-9a6f-a2d67a1d2661.png)

**Comment by arscan** [comment]
Hi @tarunkumar985, thanks for the report. Which HL7 document are you referring to?

Note that we have been refining these tests and it will better align with the exact requirement of US Core + USCDI in our next release early next week (see the `development` branch for a preview).  For example, it is ok if you do not have any Medication resources.

However, note that just because these resources do not directly contain a Patient ID, some of them are required to be present due to the 'must support' requirement of another US Core resource that references them.  For example, in the [US Core Diagnostic Report Lab](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-diagnosticreport-lab.html) profile, systems `must support` the `DiagnosticReport.performer` element, which is either a reference to a `US Core Practitioner` or `US Core Organization`.  So in order to fully support the `US Core Diagnostic Report Lab` profile you need to be able to populate that element with a reference, which means you will need to send that resource via bulk data.

cc @yunwwang

**Comment by tarunkumar985** [comment]
Thanks Rob!!

I have another doubt: For the observation resource, must support elements are status, code, subject, issued  and valueCodeableConcept .
But the test fails with message : Could not verify presence for profile http://hl7.org/fhir/us/core/StructureDefinition/us-core-smokingstatus of the following must support elements: status, code, subject, issued.

However, the application contains all the mandatory elements. 

Thanks!
![image](https://user-images.githubusercontent.com/42908566/84188452-3dbdbe80-aab1-11ea-882b-11c2e61a51f1.png)
